### ISSUE TITLE
Library Structure

### ISSUE THREAD

**Issue by corysabol** [RobDanHill/Unhingen#7]
This is an open discussion on the structure and exposed api of the library going forward.

I am thinking of something like the following:

* Unhingen - the top level of the library
  * 2D - this is all 2D graphics related code including helpers
  * 3D - same as 2D but for 3D
  * Shader - this is for all shader related code.
  * Input - this is for all input related funcitonality, mostly wraps SDL2 input stuff
  * Game - this is for some useful game related helpers such as an entity etc
  * Phys2D - 2D physics this is actual physics not fake game related physics, wrap Box2D or some sort
  * Phys3D - 3D physics; this is actual 3D physics not fake game related physics, wraps some 3D phys lib
  *  Audio - this houses all the audio wrappers
  * Utils - this is where we can cram any utilities, etc
  * Net - this is where we can have any net based classes and code
  * Animation - not sure where this should go, perhaps in it's own place.

We can add anything else we think of, but I believe that modules should all be shallow in that they are contained in their own namespaces or what not. Speaking of namespaces it may be good to look into using those to facilitate the import of several classes of code under one name? Maybe not, I'm not sure how to accomplish this in C++ in a nice manner. We will figure that out.

Each module should also house any classes that relate to them if possible, for example if we have a RigidBody2D class this should be under Phys2D along with any code that might operate on it.
Another example where modules use other modules might be the following;
2D and 3D would probably share the same texture classes and such so it might make sense to have some sort of access to the unwraped code, such as the code already written to create textures, etc. 

It's definitely best that we be very diligent with this sort of stuff now to save ourselves from duplicating functionality and to make it easier on us when we inevitably do rewrites of the framework.

**Comment by Shatterwaltz** [comment]
Looks pretty good to me. Only thing I can think of is dividing animation into 2d/3d versions.

**Comment by corysabol** [comment]
Yeah, animation should probably have a sub modules.

I started restructuring the code base a bit and writing a make file for
cross platform compilation.

I'm not sure what would be the best way to distribute the library. I might
try to mess with making it into a statically compiled library, and having
the make file have a development target and and library target.

Development for compiling the library to object files for testing, etc and
another for spitting it out to a static library.

**Comment by corysabol** [comment]
Closing as no longer relevant.
